@macro OKTO_EXIT 0

@macro OKTO_PRINT_UNSIGNED 201
@macro OKTO_PRINT_SIGNED 202
@macro OKTO_PRINT_CHAR 203
@macro OKTO_PRINT_DOUBLE_UNSIGNED 204
@macro OKTO_PRINT_DOUBLE_SIGNED 205

@macro OKTO_PRINTLN_UNSIGNED 206
@macro OKTO_PRINTLN_SIGNED 207
@macro OKTO_PRINTLN_CHAR 208
@macro OKTO_PRINTLN_DOUBLE_UNSIGNED 209
@macro OKTO_PRINTLN_DOUBLE_SIGNED 210